### ISSUE TITLE
grep: /etc/ssh/sshd_config.d/*.conf: No such file or directory on Script Start

### ISSUE THREAD

**Issue by war59312** [toralf/torutils#12]
Edit:

Sorry, kinda turned this into a mess.

Now more about confirming everything working correctly.

Hello,

I am getting the following:

```
sudo CONFIGURED_RELAYS="ServerIP:9001" ./ipv4-rules.sh start

grep: /etc/ssh/sshd_config.d/*.conf: No such file or directory
grep: /etc/ssh/sshd_config.d/*.conf: No such file or directory
```

FYI:

```
ls -la /etc/ssh/

total 568

drwxr-xr-x   4 root root   4096 Aug  1 19:41 .
drwxr-xr-x 149 root root  12288 Aug  2 17:12 ..
-rw-r--r--   1 root root     18 Jul  1 16:38 authorized_yubikeys
-rw-r--r--   1 root root 505426 Feb 25  2022 moduli
-rw-r--r--   1 root root   1650 Feb 25  2022 ssh_config
drwxr-xr-x   2 root root   4096 Apr  6  2022 ssh_config.d
-rw-r--r--   1 root root   3300 Jul  1 16:31 sshd_config
drwxr-xr-x   2 root root   4096 Mar  9  2021 sshd_config.d
-rw-r--r--   1 root root   3287 Jun  7  2022 sshd_config.ucf-dist
-rw-r--r--   1 root root   3281 Apr  6  2022 sshd_config.ucf-old
-rw-------   1 root root    513 Mar 24  2021 ssh_host_ecdsa_key
-rw-r--r--   1 root root    178 Mar 24  2021 ssh_host_ecdsa_key.pub
-rw-------   1 root root    411 Mar 24  2021 ssh_host_ed25519_key
-rw-r--r--   1 root root     98 Mar 24  2021 ssh_host_ed25519_key.pub
-rw-------   1 root root   2602 Mar 24  2021 ssh_host_rsa_key
-rw-r--r--   1 root root    570 Mar 24  2021 ssh_host_rsa_key.pub
-rw-r--r--   1 root root    342 Mar 24  2021 ssh_import_id

ls -la /etc/ssh/sshd_config.d/

total 8

drwxr-xr-x 2 root root 4096 Mar  9  2021 .
drwxr-xr-x 4 root root 4096 Aug  1 19:41 ..
```

Also, just to confirm this is working as expected...

I am using the section of "If the parsing of the Tor config (line [170](https://github.com/toralf/torutils/blob/main/ipv4-rules.sh#L170)) doesn't work for you then".

Looks like once I set:  CONFIGURED_RELAYS it seems to be working:

```
sudo watch -t ./ipv4-rules.sh

Wed, 02 Aug 2023 15:17:34 -0400
Chain INPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
76657   79M ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0            /* Wed, 02 Aug 2023 14:44:58 -0400 */
 135K  102M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp flags:!0x17/0x02 state NEW
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    1    52 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
   26  2184 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8 limit: avg 6/sec burst 5
    0     0 DROP       icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set hetzner-sysmon src
 4574  574K ufw-before-logging-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 4574  574K ufw-before-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 1995  300K ufw-after-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 ufw-after-logging-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 ufw-reject-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 ufw-track-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0            /* Wed, 02 Aug 2023 15:02:43 -0400 */
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp flags:!0x17/0x02 state NEW
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8 limit: avg 6/sec burst 5
    0     0 DROP       icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set hetzner-sysmon src
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0            /* Wed, 02 Aug 2023 15:14:08 -0400 */
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp flags:!0x17/0x02 state NEW
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8 limit: avg 6/sec burst 5
    0     0 DROP       icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set hetzner-sysmon src
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 match-set tor-trust src
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 match-set tor-multi src #conn src/32 <= 8
    0     0 SET        tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 limit: above 6/min burst 5 mode srcip-dstport htable-size 262144 htable-max 262144 htable-expire 120000 add-set tor-ddos-9001 src exist
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 match-set tor-ddos-9001 src
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 #conn src/32 > 2
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 limit: above 1/hour burst 1 mode srcip-dstport htable-size 262144 htable-max 262144 htable-expire 120000
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0            /* Wed, 02 Aug 2023 15:16:19 -0400 */
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp flags:!0x17/0x02 state NEW
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8 limit: avg 6/sec burst 5
    0     0 DROP       icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set hetzner-sysmon src
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 match-set tor-trust src
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 match-set tor-multi src #conn src/32 <= 8
    0     0 SET        tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 limit: above 6/min burst 5 mode srcip-dstport htable-size 262144 htable-max 262144 htable-expire 120000 add-set tor-ddos-9001 src exist
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 match-set tor-ddos-9001 src
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 #conn src/32 > 2
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02 limit: above 1/hour burst 1 mode srcip-dstport htable-size 262144 htable-max 262144 htable-expire 120000
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:9001 flags:0x17/0x02
```

Look good?

Well, maybe.

All the Chain and Input zeros are throwing me off.

Guess I expect numbers since I typically have between 50 and 100 connections going on.

In fact `sudo netstat -antp | grep tor` shows 66 connections right now:

```
tcp        0      0 127.0.0.1:9051          0.0.0.0:*               LISTEN      1951780/tor
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1951780/tor
tcp        0      0 ServerIP:9050     0.0.0.0:*               LISTEN      1951780/tor
tcp        0      0 127.0.0.1:44509         0.0.0.0:*               LISTEN      1951780/tor
tcp        0      0 ServerIP:33126    82.118.242.30:990       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:33258    54.38.241.3:8443        ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:58036    162.55.131.67:9100      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:44568    76.192.65.169:9001      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:53612    51.159.136.111:443      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:51578    94.130.70.89:443        ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:48026    82.165.116.173:443      ESTABLISHED 1951780/tor
tcp        0      0 127.0.0.1:44509         127.0.0.1:39794         ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:34284    162.251.116.34:443      ESTABLISHED 1951780/tor
tcp        0      0 127.0.0.1:44509         127.0.0.1:58450         ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:52272    158.220.100.158:443     ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:43746    45.142.177.89:443       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:43338    162.251.116.18:443      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:51880    37.205.8.191:443        ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:37228    45.142.232.203:9001     ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:39886    158.69.207.216:9001     ESTABLISHED 1951780/tor
tcp        0      0 127.0.0.1:44509         127.0.0.1:54096         ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:53786    104.168.32.140:443      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:43754    142.132.204.112:4443    ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:47302    217.182.196.65:443      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:58930    5.253.84.137:9100       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:38980    135.148.52.231:443      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:56298    142.132.171.253:7349    ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:47094    135.148.52.241:443      ESTABLISHED 1951780/tor
tcp        0      0 127.0.0.1:44509         127.0.0.1:36508         ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:44070    68.67.32.33:9001        ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:40064    94.130.200.167:443      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:50682    135.148.100.84:443      ESTABLISHED 1951780/tor
tcp        0      0 127.0.0.1:44509         127.0.0.1:41324         ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:32856    107.189.7.51:443        ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:37968    46.38.232.203:443       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:58416    85.119.82.151:9001      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:59956    74.208.104.100:9001     ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:55406    185.163.204.78:443      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:56630    95.216.19.41:9030       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:40790    185.241.208.179:143     ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:53434    185.21.217.32:15541     ESTABLISHED 1951780/tor
tcp        0      0 127.0.0.1:44509         127.0.0.1:34612         ESTABLISHED 1951780/tor
tcp        0      0 127.0.0.1:44509         127.0.0.1:40836         ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:49120    82.66.255.188:666       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:60394    89.58.43.207:9001       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:58542    45.88.171.100:9100      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:45738    162.55.134.240:9001     ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:54928    142.54.162.114:443      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:41822    45.141.215.4:143        ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:36054    51.81.87.113:443        ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:35578    185.241.208.170:110     ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:58158    51.68.185.82:5454       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:58814    173.212.254.192:31337   ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:34184    217.182.196.70:443      ESTABLISHED 1951780/tor
tcp        0      0 127.0.0.1:44509         127.0.0.1:48870         ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:51108    172.241.23.114:443      ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:50464    89.58.44.240:80         ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:51870    185.148.1.169:850       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:44202    162.55.91.19:443        ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:49050    217.83.20.88:9001       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:34448    66.111.2.16:9001        ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:50110    83.212.72.189:443       ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:59844    51.158.201.235:8080     ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:56918    46.105.143.215:443      ESTABLISHED 1951780/tor
tcp        0      0 127.0.0.1:44509         127.0.0.1:49072         ESTABLISHED 1951780/tor
tcp        0      0 ServerIP:35832    198.98.58.160:443       ESTABLISHED 1951780/tor
```

Edit: Restarted TOR Service to see if any changes.

`sudo watch -t ./ipv4-rules.sh` still the same.

```
sudo python3 info.py --address 127.0.0.1 --ctrlport 9051

 0.4.7.10   uptime: 00:55   flags: none
+------------------------------+-------+-------+
| Type                         |  IPv4 |  IPv6 |
+------------------------------+-------+-------+
| Inbound to OR from relay     |       |       |
| Inbound to OR from non-relay |       |       |
| Inbound to ControlPort       |       |       |
| Outbound to relay OR         |     7 |       |
| Outbound to relay non-OR     |       |       |
| Outbound as Exit             |       |       |
| Outbound unknown             |     3 |       |
+------------------------------+-------+-------+
| Total                        |    10 |       |
+------------------------------+-------+-------+
 relay OR connections                7       0
          unique ips                 7       0
```

Um,  `--ctrlport` does nada, get the same result if I lie and make up the port number.

```
sudo python3 info.py --address 127.0.0.1 --ctrlport 1111

 0.4.7.10   uptime: 16:08   flags: none
+------------------------------+-------+-------+
| Type                         |  IPv4 |  IPv6 |
+------------------------------+-------+-------+
| Inbound to OR from relay     |       |       |
| Inbound to OR from non-relay |       |       |
| Inbound to ControlPort       |       |       |
| Outbound to relay OR         |    13 |       |
| Outbound to relay non-OR     |       |       |
| Outbound as Exit             |       |       |
| Outbound unknown             |     4 |       |
+------------------------------+-------+-------+
| Total                        |    17 |       |
+------------------------------+-------+-------+
 relay OR connections               13       0
          unique ips                13       0
```

For sure using the default, as `ControlPort 9051` is set in the tor config file.

And yes using along with UFW.

OS: Ubuntu 22.04

Best,

Will

Edit: 

I'm an idiot. Sorry. I just realized I changed the default `ORPort` to  `8080`. Whoops.

Also using:

```
ServerTransportPlugin obfs4 exec /usr/bin/obfs4proxy

ServerTransportListenAddr obfs4 0.0.0.0:8000
```

Let's try with `sudo CONFIGURED_RELAYS="ServerIP:8080 ServerIP:8000" ./ipv4-rules.sh start`

```
Wed, 02 Aug 2023 17:34:16 -0400

Chain INPUT (policy DROP 6 packets, 360 bytes)
 pkts bytes target     prot opt in     out     source               destination
   31  1860 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:9051 state NEW
 203K  442M ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0            /* Wed, 02 Aug 2023 15:58:49 -0400 */
 504K  619M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
   17 21405 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp flags:!0x17/0x02 state NEW
    1    40 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
   76  6384 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8 limit: avg 6/sec burst 5
    0     0 DROP       icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set hetzner-sysmon src
    4   256 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8080 flags:0x17/0x02 match-set tor-trust src
    8   440 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8080 flags:0x17/0x02 match-set tor-multi src #conn src/32 <= 8
    0     0 SET        tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8080 flags:0x17/0x02 limit: above 6/min burst 5 mode srcip-dstport htable-size 262144 htable-max 262144 htable-expire 120000 add-set tor-ddos-8080 src exist
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8080 flags:0x17/0x02 match-set tor-ddos-8080 src
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8080 flags:0x17/0x02 #conn src/32 > 2
    6   360 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8080 flags:0x17/0x02 limit: above 1/hour burst 1 mode srcip-dstport htable-size 262144 htable-max 262144 htable-expire 120000
   20  1136 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8080 flags:0x17/0x02
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8000 flags:0x17/0x02 match-set tor-trust src
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8000 flags:0x17/0x02 match-set tor-multi src #conn src/32 <= 8
   94  5660 SET        tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8000 flags:0x17/0x02 limit: above 6/min burst 5 mode srcip-dstport htable-size 262144 htable-max 262144 htable-expire 120000 add-set tor-ddos-8000 src exist
  302 18148 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8000 flags:0x17/0x02 match-set tor-ddos-8000 src
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8000 flags:0x17/0x02 #conn src/32 > 2
  347 20680 DROP       tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8000 flags:0x17/0x02 limit: above 1/hour burst 1 mode srcip-dstport htable-size 262144 htable-max 262144 htable-expire 120000
   68  3952 ACCEPT     tcp  --  *      *       0.0.0.0/0            ServerIP       tcp dpt:8000 flags:0x17/0x02
15524 2032K ufw-before-logging-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
15524 2032K ufw-before-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 7313 1091K ufw-after-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    6   360 ufw-after-logging-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    6   360 ufw-reject-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    6   360 ufw-track-input  all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

There we go. See DROP and ACCEPT for TOR. :)

```
sudo python3 info.py --address 127.0.0.1 --ctrlport 9051

 0.4.7.10   uptime: 43:49   flags: none
+------------------------------+-------+-------+
| Type                         |  IPv4 |  IPv6 |
+------------------------------+-------+-------+
| Inbound to OR from relay     |     1 |       |
| Inbound to OR from non-relay |       |       |
| Inbound to ControlPort       |       |       |
| Outbound to relay OR         |    22 |       |
| Outbound to relay non-OR     |       |       |
| Outbound as Exit             |       |       |
| Outbound unknown             |     6 |       |
+------------------------------+-------+-------+
| Total                        |    29 |       |
+------------------------------+-------+-------+
 relay OR connections               23       0
          unique ips                23       0
```

Well, your ps.py not really working it seems:

```
sudo python3 ps.py --address 127.0.0.1 --ctrlport 9051

port   # opened closed    max        ( "" 127.0.0.1:9051, 29 conns 0.00 sec )
```

The screen just keeps refreshing and shows that above.

So tried using the real server IP and I get:

```
sudo python3 ps.py --address ServerIP --ctrlport 9051
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/stem/socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/ps.py", line 205, in <module>
    main()
  File "/home/will/ps.py", line 48, in main
    with Controller.from_port(address=args.address, port=args.ctrlport) as controller:
  File "/usr/local/lib/python3.10/dist-packages/stem/control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "/usr/local/lib/python3.10/dist-packages/stem/socket.py", line 503, in __init__
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/stem/socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "/usr/local/lib/python3.10/dist-packages/stem/socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused
```

Recommend cleanly handling this exception. Not sure why the connection was refused, unless this script itself is blocking it.

```
sudo python3 ps.py --address ServerIP --ctrlport 905151

Traceback (most recent call last):
  File "/home/will/ps.py", line 205, in <module>
    main()
  File "/home/will/ps.py", line 48, in main
    with Controller.from_port(address=args.address, port=args.ctrlport) as controller:
  File "/usr/local/lib/python3.10/dist-packages/stem/control.py", line 1026, in from_port
    raise ValueError('Invalid IP address: %s' % address)
ValueError: Invalid IP address: ServerIP
will@pihole:~$ sudo python3 ps.py --address ServerIP --ctrlport 9051
```

Whoops I copied and pasted and forgot to change out ServerIP and a little different exception that needs to be handled.

TCP 9051 via UFW is allowed.

See:

```
sudo ipset list -t
Name: hetzner-sysmon
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x98027467
Size in memory: 400
References: 1
Number of entries: 5

Name: tor-trust
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0xbf20ae66
Size in memory: 800
References: 2
Number of entries: 15

Name: tor-multi
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x8fecfcf0
Size in memory: 25240
References: 2
Number of entries: 825

Name: tor-ddos-9001
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 262144 timeout 86400 bucketsize 12 initval 0xcf13be95
Size in memory: 200
References: 0
Number of entries: 0

Name: tor-ddos-8080
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 262144 timeout 86400 bucketsize 12 initval 0x69266d82
Size in memory: 200
References: 2
Number of entries: 0

Name: tor-ddos-8000
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 262144 timeout 86400 bucketsize 12 initval 0x1100b653
Size in memory: 328
References: 2
Number of entries: 2
```

**Comment by toralf** [comment]
The grep output is harmless and fixed in 7c3fcb0.

The ps.py docs was updated too: cfa6ed6

**Comment by war59312** [comment]
Perfect, thank you.

And since no mention by you. I assume my logs above all look good and everything working as expected?

**Comment by toralf** [comment]
> Perfect, thank you.
> 
> And since no mention by you. I assume my logs above all look good and everything working as expected?

Well, it seems you can reach the control port 9051 via internet - I personally prefer to have this port only open for 127.0.0.1 only. Otherwise , looks all pretty normal.

I will take a look later, if the Python exception can be catched.

**Comment by war59312** [comment]
It's a fake-out. 

Limited to my private IP range elsewhere. And this Ubuntu 22.04 VM is behind a pfSense firewall within its own VLAN.

Thinking I may even get more creative and run it on [Tails ](https://tails.net/)and just reboot every 30 days or something to be sure 100% no private data is being collected.

I'll consider this closed. Thanks again and thanks for looking at the Python exceptions.
